Add methods for getting file data from the vfs
wannkunstbeikor/Galanthus pull request #1
Opened 2024-08-08 00:22 UTC by CosmicDreamsOfCode

Only things to really note are that i had to add something to let the method for getting the file data know what encryption to use, probably better like this anyway 
and that obviously i can't get any oodle slices since we don't support that right now

2024-08-08 00:24 UTC, CosmicDreamsOfCode commented
the combine byte array methood should probably be moved somewhere else or changed to something for blocks if you'd prefer the data be returned as a block, i feel that'll probably be the most contentious bit of this PR

2024-08-08 18:49 UTC, wannkunstbeikor requested changes

2024-08-08 18:49 UTC, wannkunstbeikor commented on Galanthus/SdfToc.cs
> +            sdfPath = Path.Combine(dataDir, sdfName);
check if file exists, since the part e stuff is downloaded on demand

2024-08-08 18:49 UTC, wannkunstbeikor commented on Galanthus/SdfToc.cs
> +                    if (toc.m_encryptionMethod == "XTEA+DES")
use m_header.Version, like how its done in SdfToc.Read

2024-08-08 18:49 UTC, wannkunstbeikor commented on Galanthus/SdfToc.cs
> +        return CombineByteArray(fileData.ToArray());
yeah this should return Block<byte>, i would maybe iterate through the Slices and get the complete size (dont forgot to check if the file exist and dds header) and then create one big block which u just slice

2024-08-11 19:46 UTC, wannkunstbeikor requested changes
just some small minor changes, after u fix them im going to merge it thanks a lot

2024-08-11 19:46 UTC, wannkunstbeikor commented on Galanthus/GameManager.cs
> +    public static Byte[] TryGetFileBytes(string filePath, string inDirectory)
can u make this a Block<byte> as well

2024-08-11 19:46 UTC, wannkunstbeikor commented on Galanthus/SdfToc.cs
> +                using (DataStream stream = BlockStream.FromFile(sdfPath))
there should be an overload that takes in the offset and size, so u dont need to load the whole file into a block
`BlockStream.FromFile(sdfPath, dataSlice.Offset, dataSlice.CompressedSize)`

2024-08-11 19:46 UTC, wannkunstbeikor commented on Galanthus/SdfToc.cs
> +                            outBuffer.Shift((int)dataSlice.DecompressedSize);
yeah move it out like u showed on discord

2024-08-11 19:46 UTC, wannkunstbeikor commented on GalanthusCli/Program.cs
> +        else
i think u didnt want to commit this

2024-08-11 22:18 UTC, CosmicDreamsOfCode commented on Galanthus/GameManager.cs
> +    public static Byte[] TryGetFileBytes(string filePath, string inDirectory)
i thought it would be better to return a byte[] for easier writing to a file, if it returns a block it would be harder to use this function from another program i think

2024-08-12 14:24 UTC, wannkunstbeikor commented on Galanthus/GameManager.cs
> +    public static Byte[] TryGetFileBytes(string filePath, string inDirectory)
its just one call to Block.ToArray, so not really much harder and u can also use the Block if u want, if u return the array u cant convert it back to a Block

2024-08-12 17:56 UTC, CosmicDreamsOfCode commented on Galanthus/GameManager.cs
> +    public static Byte[] TryGetFileBytes(string filePath, string inDirectory)
wouldn't whoever was using the library need to also use the stream utils then?

2024-08-12 17:59 UTC, wannkunstbeikor commented on Galanthus/GameManager.cs
> +    public static Byte[] TryGetFileBytes(string filePath, string inDirectory)
yeah, but the plan is that its going to be nuget packages, so it will automatically install itself if u reference galanthus

2024-08-12 19:53 UTC, CosmicDreamsOfCode commented on Galanthus/GameManager.cs
> +    public static Byte[] TryGetFileBytes(string filePath, string inDirectory)
ahh

2024-08-12 20:08 UTC, wannkunstbeikor approved these changes

2024-08-12 20:15 UTC, merged